### ISSUE TITLE
you cookie lib cant overwrite same cookie key

### ISSUE THREAD

**Issue by sunfuze** [poppinss/node-cookie#1]
I have used adonis for my app, I found that i cant overwrite same cookie key. For example, 
old
```
# old request cookie
SESSION:111;DEVICE_INFO:111
```
response, 
```
# response set cookie
set-cookie: SESSION:111;DEVICE_INFO:111
set-cookie: SESSION:222
```
then, in the browser, cookie is 
```
SESSION:111;DEVICE_INFO:111;SESSION:222
```

**Comment by thetutlage** [comment]
Browsers will use the latest cookie if duplicate found. Let me know if this is causing any issues.
