### ISSUE TITLE
Use keygrip version 1.0.1 rather then repository release

### ISSUE THREAD

**Issue by nallown** [poppinss/node-cookie#2]
This module uses the keygrip master repository which has major API changes compared to the npm release this causes other modules to break since they use the npm release that uses the release API.

I know that this module makes use of the new API functions which aren't available in the npm releases but it also causes conflicts with other modules causing them to break.

Is there any chance for this module to use the keygrip npm releases rather then the master repository?

**Comment by thetutlage** [comment]
How this module can break other modules?

And ideally it should be an issue with keygrip to release the latest version.

**Comment by nallown** [comment]
The master repository which hasn't been released yet returns a Buffer when you hash a value. The npm releases return a string so basically all of the other modules that used keygrip end up working with a buffer expecting it to be a string. They end up storing a buffer as a cookie rather then a hash string.

**Comment by thetutlage** [comment]
Got rid of keygrip in the latest commit
