### ISSUE TITLE
Adonis framework installation error

### ISSUE THREAD

**Issue by GEGman** [poppinss/node-cookie#4]
Hi @thetutlage  
Thank you for adonis. :) I have an installation error on windows machine.
It's linked with this row in package file:
` "keygrip": "git://github.com/crypto-utils/keygrip.git"`
Could you change it to standard description with version?

npm log:
> npm install node-cookie
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-cookie"
> npm ERR! node v7.3.0
> npm ERR! npm  v3.10.10
> npm ERR! path C:\npm-cache\_git-remotes\git-github-com-crypto-utils-keygrip-git-7cf0e7e1\HEAD
> npm ERR! code ENOENT
> npm ERR! errno -4058
> npm ERR! syscall scandir
> 
> npm ERR! enoent ENOENT: no such file or directory, scandir 'C:\npm-cache\_git-remotes\git-github-com-crypto-utils-keygrip-git-7cf0e7e1\HEAD'
> npm ERR! enoent ENOENT: no such file or directory, scandir 'C:\npm-cache\_git-remotes\git-github-com-crypto-utils-keygrip-git-7cf0e7e1\HEAD'
> npm ERR! enoent This is most likely not a problem with npm itself
> npm ERR! enoent and is related to npm not being able to find a file.
> npm ERR! enoent
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\OpenServerLight\domains\localhost\adonis_basic_server\npm-debug.log

**Comment by thetutlage** [comment]
Got rid of keygrip in the latest commit
