### ISSUE TITLE
Bug in Cookie._append

### ISSUE THREAD

**Issue by richie3366** [poppinss/node-cookie#8]
I found a weird bug affecting new visitors having no cookie at their first request (my project uses adonuxt ssr).

```
ERROR  cookies.map is not a function
  at Object.Cookie._append (/var/www/shared/node_modules/node-cookie/src/Cookie/index.js:164:39)
  at Object.Cookie.create (/var/www/shared/node_modules/node-cookie/src/Cookie/index.js:389:10)
  at Response.cookie (/var/www/shared/node_modules/@adonisjs/framework/src/Response/index.js:503:16)
```
And indeed, when you look at that line of code, you see that the `cookies` variable is not affected by the else-case of the ternary condition: 
https://github.com/poppinss/node-cookie/blob/07f12f663338069d7e2d07526bf795e5b3a24353/index.js#L162-L166

So, my quick workaround was to change it like so:
```javascript
  Array.isArray(cookies) ? cookies.push(cookie) : (cookies = [cookies]).push(cookie)
```
And it solved it. (I also changed the cookies declaration to `let` instead of `const`)

I don't know if you are comfortable with parenthesis assignment allowing to use directly the assigned value.

If so, I can make a PR to merge my fix into the lib. ;)

**Comment by thetutlage** [comment]
I don't see how `re-assigning` to cookie variable helps here. Also, I would love to see a test that reproduces this issue within the context of the HTTP server `res` object

**Comment by richie3366** [comment]
Hello @thetutlage, you may have missed the notification (or be busy at that time), but I provided the test case you asked for.

The current code does nothing to the `cookies` var when it is already defined as a non-array, you just need to read carefully the line to notice it.

I hope that you have everything you need to approve this merge.
Thanks!
